package main.hospital;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;

@Entity
public class Nurse {
    // @GeneratedValue(strategy = GenerationType.IDENTITY) ensures the 'id' is
    // automatically generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty("id")
    private Integer id;

    @JsonProperty("name")
    private String name;

    @JsonProperty("user")
    private String user;

    @JsonProperty("password")
    private String password;

    @Lob
    @JsonProperty("profile_image")
    private byte[] profileImage;
    
    // Constructor with parameters for initializing a Nurse object.
    public Nurse(Integer id, String name, String user, String password, byte[] profileImage) {
        this.id = id;
        this.name = name;
        this.user = user;
        this.password = password;
        this.profileImage = profileImage;
    }

    // Default constructor for deserialization (converting JSON to a Java Object).
    public Nurse() {

    }

    // Constructor for initializing a Nurse object with user credentials.
    public Nurse(String user, String password) {
        this.user = user;
        this.password = password;
    }

    // Getters and setters.
    @JsonProperty("id")
    public Integer getId() {
        return id;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("user")
    public String getUser() {
        return user;
    }

    @JsonProperty("password")
    public String getPassword() {
        return password;
    }
    
    @JsonProperty("profile_image")
    public byte[] getProfileImage() {
        return profileImage;
    }

    @JsonProperty("id")
    public void setId(Integer id) {
        this.id = id;
    }

    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonProperty("user")
    public void setUser(String user) {
        this.user = user;
    }

    @JsonProperty("password")
    public void setPassword(String password) {
        this.password = password;
    }
    
    @JsonProperty("profile_image")
    public void setProfileImage(byte[] profileImage) {
        this.profileImage = profileImage;
    }
}
