name: Spring Boot CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1: Code checkout.
      - name: Checkout code
        uses: actions/checkout@v2

      # 2: JDK configuration
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  

      # 3: give permisions in order to execute mvnw.
      - name: Give execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean compile

      # 4 Execute all JUnit tests from the test directory.
      - name: Run JUnit tests
        run: ./mvnw testtest
